### PR TITLE
Added Anbox Support!

### PR DESCRIPTION
**Pull request by joelselvaraj**
Anbox feature added to kernel.

**How to use:** (Kindly mention it xda forum)

SSH into phone from computer `ssh phablet@10.15.19.82` or use the terminal app in phone directly
- `sudo mount -o rw,remount /`
- `sudo apt update`
- `sudo apt install anbox-ubuntu-touch`
- `sudo rm /usr/bin/anbox-tool` (We need a patched version to use it as device is not officially supported)
- `sudo wget -O /usr/bin/anbox-tool https://gist.githubusercontent.com/joelselvaraj/ae7e5622297e70face37323759742edc/raw/32862160aa39acd4d8cb0085627bb1cf736ef1d1/anbox-tool` (Patched version)
- `sudo chmod +x /usr/bin/anbox-tool`
- `anbox-tool install`

Done! You must be able to see the default apps available in the ubports apps screen.

**To install new app:**
SSH into phone from computer `ssh phablet@10.15.19.82` or use the terminal app in phone directly
- `sudo mount -o rw,remount /`
- `sudo apt update`
- `sudo apt install android-tools-adb` (Needed for installing new app)
- Download the apk file in your phone
- `adb install /home/phablet/Downloads/my-app.apk`
- The app must now be installed and visible in the ubports apps screen.

**!!WARNING!!**
Ubports Anbox feature is in like pre-alpha state! Use it in your own risk! Very few apps work as expected. And a lot of bugs! Use it for testing purposes only. Have fun!

**Reference** : http://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html

### CODE REVIEW

**Comment by joelselvaraj** [comment]
Bro, Can you kindly add me as a member in the 'ubports-mido' organization? I would love to contribute.

**Comment by mehranz** [comment]
Hello
When I'm running `anbox-tool install` it says `Anbox kernel is not installed! Please flash this first!`
what should i do?

**UPDATE**: my bad! i taught v1.1 pre-alpha is newer than v1.0-alpha 😬. in version 1.0 alpha everything works!

**Comment by gopikrishnanrmg** [comment]
Did you follow the steps mentioned in XDA?

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by mehranz** [comment]
yes, I did.

**Pull request merged**
